import { Geist, Geist_Mono, Lora } from 'next/font/google';
import './globals.css';
import NavBar from './components/shared/navbar';
import Footer from './components/shared/footer';

const geistSans = Lora({
  weight: ['400', '500', '600', '700'],
  subsets: ['cyrillic'],
  style: ['normal', 'italic'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body
        className={`${geistSans.variable}  min-h-dvh flex flex-col justify-between`}
      >
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
